# syntax=docker/dockerfile:1
FROM archlinux:base-devel

# Update (-Syu) only for the first run
RUN pacman -Syu --noconfirm

RUN pacman -S git --noconfirm

RUN useradd -ms /bin/bash -G wheel builder
# makepkg requires a sudoer but not the root user
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Because we can: test also ArchLinux's Eigen library
RUN pacman -S --noconfirm eigen

USER builder
WORKDIR /home/builder
RUN git clone https://github.com/archlinux/svntogit-packages --depth 1 --branch "packages/eigen"
WORKDIR /home/builder/svntogit-packages/trunk
RUN makepkg -si --noconfirm

COPY context .

RUN g++ -Ipkg/eigen/usr/include/eigen3 -O0 -g3 -Wall -o"build.o" eigenversion.cpp && \
    chmod +x build.o && \
    ./build.o
RUN g++ -I/usr/include/eigen3 -O0 -g3 -Wall -o"install.o" eigenversion.cpp && \
    chmod +x install.o && \
    ./install.o

