# syntax=docker/dockerfile:1
FROM cuda-arch

ENV GLIBC_VERSION 2.35-r0

#RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata


# Update (-Syu) only for the first run
RUN pacman -Syu --noconfirm
RUN pacman -S git x11vnc xorg-server --noconfirm

RUN useradd -ms /bin/bash -G wheel builder
#RUN echo "builder:docker" | chpasswd
# makepkg requires a sudoer but not the root user
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

WORKDIR /opt
RUN git clone https://aur.archlinux.org/yay-git.git
RUN chown -R builder:builder ./yay-git

USER builder
WORKDIR /opt/yay-git
RUN makepkg -si --noconfirm


WORKDIR /home/builder

USER builder
#RUN makepkg -si --noconfirm

RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S python-numpy
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S python-opengl
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S python-sphinx
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S 'python-sphinxcontrib-bibtex>=0.3.5'

COPY context .

# follow https://aur.archlinux.org/packages/python-griddataformats#comment-886230
# griddataformats.sh is required by mdaanlaysis
RUN ./install_python-griddataformats.sh

RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S 'python-mdanalysis>=0.16'
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S 'hdf5-openmpi: File format to store scientific data(openmpi version)'
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S 'boost>=1.67'
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S 'cmake>=3.4'
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S 'fftw>=3'
RUN yay --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps -S 'openmpi>=1.2'

#RUN yay -S espressomd-git --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm
RUN ./install_espressomd-git.sh

